CREATE DATABASE NovoVarejoDb
GO

USE NovoVarejoDb
GO

CREATE TABLE Pais 
(
	PaisId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomePais NVARCHAR(30) UNIQUE NOT NULL
);
GO

CREATE TABLE Estado
(
	EstadoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeEstado NVARCHAR(30) UNIQUE NOT NULL
);
GO

CREATE TABLE Cidade 
(
	CidadeId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeCidade NVARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE CargoUsuario
(
	CargoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeCargo VARCHAR(20) UNIQUE NOT NULL
);
GO

CREATE TABLE StatusUsuario 
(
	StatusUsuarioId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeStatus VARCHAR(20) UNIQUE NOT NULL
);
GO

CREATE TABLE Usuario 
(
	UsuarioId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	StatusUsuarioId UNIQUEIDENTIFIER NOT NULL,
	CargoUsuarioId UNIQUEIDENTIFIER NOT NULL,
	Nome NVARCHAR(50),
	Email VARCHAR(255) UNIQUE,
	CPF VARCHAR(12) UNIQUE,
	DataNascimento DATETIME2,

	CONSTRAINT FK_Usuario_SatatusUsuario_StatusId FOREIGN KEY (StatusUsuarioId) REFERENCES StatusUsuario(StatusUsuarioId),
	CONSTRAINT FK_Usuario_CargoUsuario_CargoId FOREIGN KEY (CargoUsuarioId) REFERENCES CargoUsuario(CargoId)
);
GO

CREATE TABLE EnderecoUsuario
(
	EnderecoUsuarioId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	Logradouro NVARCHAR(150),
	EstadoId UNIQUEIDENTIFIER NOT NULL,
	CidadeId UNIQUEIDENTIFIER NOT NULL,
	PaisId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_EnderecoUsuario_Usuario_UsuarioId FOREIGN KEY (UsuarioId) REFERENCES Usuario(UsuarioId),
	CONSTRAINT FK_EnderecoUsuario_Estado_EstadoId FOREIGN KEY (EstadoId) REFERENCES Estado(EstadoId),
	CONSTRAINT FK_EnderecoUsuario_Cidade_CidadeId FOREIGN KEY (CidadeId) REFERENCES Cidade(CidadeId),
	CONSTRAINT FK_EnderecoUsuario_Pais_PaisId FOREIGN KEY (PaisId) REFERENCES Pais(PaisId)
);
GO

CREATE TABLE LogUsuario
(
	LogUsuarioId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	StatusUsuarioId UNIQUEIDENTIFIER NOT NULL,
	CargoUsuarioId UNIQUEIDENTIFIER NOT NULL,
	EnderecoUsuarioId UNIQUEIDENTIFIER NOT NULL,
	NomeUsuario NVARCHAR(50),
	Email VARCHAR(255) UNIQUE,
	CPF VARCHAR(12) UNIQUE,
	DataNascimento DATETIME2, 
	DescricaoLog NVARCHAR(100),
	DataLog DATETIME2 DEFAULT GETDATE(),

	CONSTRAINT FK_LogUsuario_Usuario_UsuarioId FOREIGN KEY (UsuarioId) REFERENCES Usuario(UsuarioId),
	CONSTRAINT FK_LogUsuario_StatusUsuario_StatusId FOREIGN KEY (StatusUsuarioId) REFERENCES StatusUsuario(StatusUsuarioId),
	CONSTRAINT FK_LogUsuario_CargoUsuario_CargoId FOREIGN KEY (CargoUsuarioID) REFERENCES CargoUsuario(CargoId),
	CONSTRAINT FK_LogUsuario_EnderecoUsuario_EnderecoUsuarioId FOREIGN KEY (CargoUsuarioId) REFERENCES EnderecoUsuario(EnderecoUsuarioId) 
);
GO


CREATE TABLE CategoriaProduto 
(
	CategoriaId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeCategoria NVARCHAR(30) UNIQUE NOT NULL
);
GO

CREATE TABLE StatusProduto
(
	StatusId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeStatus NVARCHAR(30) UNIQUE NOT NULL
);
GO

CREATE TABLE Produto
(
	ProdutoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeProduto NVARCHAR(50) UNIQUE NOT NULL,
	Preco DECIMAL(10, 2) NOT NULL,
	StatusProdutoId UNIQUEIDENTIFIER NOT NULL,
	CategoriaProdutoId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Produto_StatusProduto_StatusId FOREIGN KEY (StatusProdutoId) REFERENCES StatusProduto(StatusId),
	CONSTRAINT FK_Produto_CategoriaProduto_CategoriaId FOREIGN KEY (CategoriaProdutoId) REFERENCES CategoriaProduto(CategoriaId)
);
GO

CREATE TABLE EstoqueProduto
(
	UnidadeProdutoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ProdutoId UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT FK_EstoqueProduto_Produto_ProdutoId FOREIGN KEY (ProdutoId) REFERENCES Produto(ProdutoId)
);
GO

CREATE TABLE Carrinho
(
	CarrinhoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ProdutoId UNIQUEIDENTIFIER NULL,

	CONSTRAINT FK_Carrinho_Produto_ProdutoId FOREIGN KEY (ProdutoId) REFERENCES Produto(ProdutoId)
);
GO

CREATE TABLE LogCarrinho
(
	CarrinhoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ProdutoId UNIQUEIDENTIFIER NOT NULL,
	DescricaoLog NVARCHAR(100) NOT NULL,
	DataLog DATETIME2 DEFAULT GETDATE(),

	CONSTRAINT FK_LogCarrinho_Produto_ProdutoId FOREIGN KEY (ProdutoId) REFERENCES Produto(ProdutoId)

);
GO

CREATE TABLE LogEstoqueProduto
(
	LogEstoqueProdutoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UnidadeProdutoId UNIQUEIDENTIFIER NOT NULL,
	ProdutoId UNIQUEIDENTIFIER NOT NULL,
	DescricaoLog NVARCHAR(100) NOT NULL,
	DataLog DATETIME2 DEFAULT GETDATE(),

	CONSTRAINT FK_LogEstoqueProduto_EstoqueProduto_UnidadeProdutoId FOREIGN KEY (UnidadeProdutoId) REFERENCES EstoqueProduto(UnidadeProdutoId),
	CONSTRAINT FK_LogEstoqueProduto_Produto_ProdutoId FOREIGN KEY (ProdutoId) REFERENCES Produto(ProdutoId)
);
GO

CREATE TABLE StatusPedido 
(
	StatusPedidoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	NomeStatus VARCHAR(20)
);
GO

CREATE TABLE Pedido
(
	PedidoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	EnderecoUsuarioId UNIQUEIDENTIFIER NOT NULL,
	StatusPedidoId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Pedido_Usuario_UsuarioId FOREIGN KEY (UsuarioId) REFERENCES Usuario(UsuarioId),
	CONSTRAINT FK_Pedido_EnderecoUsuario_EnderecoUsuarioId FOREIGN KEY (EnderecoUsuarioId) REFERENCES EnderecoUsuario(EnderecoUsuarioId),
	CONSTRAINT FK_Pedido_StatusPedido_StatusPedidoId FOREIGN KEY (StatusPedidoId) REFERENCES StatusPedido(StatusPedidoId),
);
GO

CREATE TABLE LogPedido
(
	LogPedidoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	EnderecoUsuarioId UNIQUEIDENTIFIER NOT NULL,
	StatusPedidoId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_LogPedido_Usuario_UsuarioId FOREIGN KEY (UsuarioId) REFERENCES Usuario(UsuarioId),
	CONSTRAINT FK_LogPedido_EnderecoUsuario_EnderecoUsuarioId FOREIGN KEY (EnderecoUsuarioId) REFERENCES EnderecoUsuario(EnderecoUsuarioId),
	CONSTRAINT FK_LogPedido_StatusPedido_StatusPedidoId FOREIGN KEY (StatusPedidoId) REFERENCES StatusPedido(StatusPedidoId),
);
GO

CREATE TABLE ProdutoCarrinho
(
	ProdutoId UNIQUEIDENTIFIER NOT NULL,
	CarrinhoId UNIQUEIDENTIFIER NOT NULL,
	
	CONSTRAINT PK_ProdutoCarrinho_ProdutoId_CarrinhoId PRIMARY KEY (ProdutoId, CarrinhoId),
	CONSTRAINT FK_ProdutoCarrinho_Produto_ProdutoId FOREIGN KEY (ProdutoId) REFERENCES Produto(ProdutoId),
	CONSTRAINT FK_ProdutoCarrinho_CarrinhoId_CarrinhoId FOREIGN KEY (CarrinhoId) REFERENCES Carrinho(CarrinhoId)
);
GO

CREATE TABLE PedidoProduto
(
	ProdutoId UNIQUEIDENTIFIER NOT NULL,
	PedidoId UNIQUEIDENTIFIER NOT NULL,
	
	CONSTRAINT PK_PedidoProduto_ProdutoId_PedidoId PRIMARY KEY (ProdutoId, PedidoId),
	CONSTRAINT FK_PedidoProduto_Produto_ProdutoId FOREIGN KEY (ProdutoId) REFERENCES Produto(ProdutoId),
	CONSTRAINT FK_PedidoProduto_Pedido_PedidoId FOREIGN KEY (PedidoId) REFERENCES Pedido(PedidoId)
);
GO

CREATE TABLE StatusPagamento
(
	StatusPagamentoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeStatus VARCHAR(20)
);
GO

CREATE TABLE Pagamento
(
	PagamentoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Valor DECIMAL(10, 2),
	PedidoId UNIQUEIDENTIFIER NOT NULL,
	StatusPagamentoId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Pagamento_Pedido_PedidoId FOREIGN KEY (PedidoId) REFERENCES Pedido(PedidoId),
	CONSTRAINT FK_Pagamento_StatusPagamento_StatusPagamentoId FOREIGN KEY (StatusPagamentoId) REFERENCES StatusPagamento(StatusPagamentoId),
);
GO

CREATE TABLE LogPagamento
(
	LogPagamentoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Valor DECIMAL(10, 2),
	PedidoId UNIQUEIDENTIFIER NOT NULL,
	StatusPagamentoId UNIQUEIDENTIFIER NOT NULL,
	Descricao NVARCHAR(100) NOT NULL,
	DataLog DATETIME2 DEFAULT GETDATE(),

	CONSTRAINT FK_LogPagamento_Pedido_PedidoId FOREIGN KEY (PedidoId) REFERENCES Pedido(PedidoId),
	CONSTRAINT FK_LogPagamento_StatusPagamento_StatusPagamentoId FOREIGN KEY (StatusPagamentoId) REFERENCES StatusPagamento(StatusPagamentoId),
);
GO

CREATE TABLE StatusEntrega
(
	StatusEntregaId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomeStatus VARCHAR(20)
);
GO

CREATE TABLE Entrega
(
	EntregaId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	PedidoId UNIQUEIDENTIFIER NOT NULL,
	StatusEntregaId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Entrega_Pedido_PedidoId FOREIGN KEY (PedidoId) REFERENCES Pedido(PedidoId),
	CONSTRAINT FK_Entrega_StatusEntrega_StatusEntregaId FOREIGN KEY (StatusEntregaId) REFERENCES StatusEntrega(StatusEntregaId),
);
GO

CREATE TABLE LogEntrega
(
	LogEntregaId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	EntregaId UNIQUEIDENTIFIER NOT NULL,
	PedidoId UNIQUEIDENTIFIER NOT NULL,
	StatusEntregaId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_LogEntrega_Pedido_PedidoId FOREIGN KEY (PedidoId) REFERENCES Pedido(PedidoId),
	CONSTRAINT FK_LogEntrega_StatusEntrega_StatusEntregaId FOREIGN KEY (StatusEntregaId) REFERENCES StatusEntrega(StatusEntregaId),
)